sexes = ["Man", "Woman"]

professions = [
    "Actor",
    "Agronomist",
    "Anchorman",
    "Biologist",
    "Businessman",
    "Cartographer",
    "Chemist",
    "Constructor",
    "Cook",
    "Dentist",
    "Designer",
    "Ecologist",
    "Electrician",
    "Firefighter",
    "Geologist",
    "Guide",
    "History Teacher",
    "Interpreter",
    "Journalist",
    "Judge",
    "Landscape Designer",
    "Lawyer",
    "Macroeconomist",
    "Marketer",
    "Mechanic",
    "Military Pilot",
    "Model",
    "Musician",
    "Nuclear Physicist",
    "Pharmacist",
    "Philosopher",
    "Photographer",
    "Psychologist",
    "Physicist",
    "Pizza Delivery Guy",
    "Policeman",
    "Psychic",
    "Reality Show Actor",
    "Retailer",
    "Sexologist",
    "Soldier",
    "Surgeon",
    "Survival Instructor",
    "Tattoo Artist",
    "Thief",
    "Video Engineer",
    "Virologist",
    "Vlogger",
    "Writer",
    "Zoologist"
]

phobias = [
    "Acrophobia",
    "Aqua-phobia",
    "Arachnophobia",
    "Aulophobia",
    "Bibliophobia",
    "Claustrophobia",
    "Coulrophobia",
    "Cyberphobia",
    "Cynophobia",
    "Demonophobia",
    "Entomophobia",
    "Glossophobia",
    "Hemophobia",
    "Herpetophobia",
    "Hoplophobia",
    "Musophobia",
    "Mysophobia",
    "No phobia",
    "No phobia",
    "No phobia",
    "No phobia",
    "No phobia",
    "No phobia",
    "No phobia",
    "Ornithophobia",
    "Phasmaphobia",
    "Tetraphobia",
    "Topophobia",
    "Turophobia",
    "Zoophobia"
]

hobbies = [
    "18th Century Gunsmith",
    "Alpinism",
    "Amateur Electronics",
    "Amateur Radio",
    "Archery",
    "Camping",
    "Card Tricks",
    "Carpentry",
    "Chess",
    "Clockmaker",
    "Coin Collecting",
    "Culinary",
    "Dancing",
    "Drawing",
    "Fishing",
    "Football",
    "Golfing",
    "Homeopathy",
    "Hunting",
    "Martial Arts",
    "Photography",
    "Picking Mushrooms",
    "Plant Cultivation",
    "Playing the Harmonica",
    "Sailing",
    "Shoemaker",
    "Singing",
    "Study of Topographic Maps",
    "Target Practice",
    "Weaponsmith"
]

character_traits = [
    "Brave",
    "Chatful",
    "Convivial",
    "Courageous",
    "Creative",
    "Cunning",
    "Deceitful",
    "Demanding",
    "Depressive",
    "Despicable",
    "Egoistic",
    "Enclosed",
    "Exuberant",
    "Failsafe",
    "Funny",
    "Furious",
    "Honest",
    "Hysterical",
    "Irritable",
    "Narcissistic",
    "Nice",
    "Purposeful",
    "Pushy",
    "Reliable",
    "Ruthless",
    "Selfish",
    "Shy",
    "Slow",
    "Stubborn",
    "Talkative"
]

health_conditions = [
    "Acne",
    "Adenoids",
    "Alcoholism",
    "Allergic Asthma",
    "Alzheimer's disease",
    "Anorexia",
    "Anxiety",
    "Blind",
    "Daltonism",
    "Deaf",
    "Defective Speech",
    "Diabetes",
    "Drug Addiction",
    "Flatfoot",
    "Genetic diseases",
    "Haemorrhoids",
    "Hemophilia",
    "HIV (5 years)",
    "Lung Cancer (3 years)",
    "Migraines",
    "Obesity",
    "Orthorexia",
    "Perfectly Healthy",
    "Perfectly Healthy",
    "Psoriasis",
    "Rotavirus",
    "Sterile",
    "Strabismus",
    "Sun Allergy",
    "Thalassemia"
]


additional_info = [
    "Believes in Aliens",
    "Believes in Psychics",
    "Can Make Alcohol out of anything",
    "Can Make Bows and Spears",
    "Got out of a Deserted Island",
    "Has a Biology Degree",
    "Has an Architecture Degree",
    "Has Psychic Abilities",
    "Knows 5 languages",
    "Knows about the Weapon Stock",
    "Knows all of Shakespeare's Plays",
    "Knows Everything about Computers",
    "Knows Morse Code",
    "Knows Sign Language",
    "Knows the Night Sky",
    "Master of Sports in Boxing",
    "Raised by the Farmer's Family",
    "Read All the Books about Zombies",
    "Read Harry Potter 5 times",
    "Robbed his/her Grandpa",
    "Served in Church",
    "Studied in a Medical University for 4 years",
    "Studied Water Cleaning",
    "Traveled the World",
    "Was in the Survival Camp for 3 years",
    "Was Raised in a Geologist Family",
    "Went Through the Psychologist Course",
    "Won a Lottery",
    "Worked in a Hospital",
    "Worked in the Theater"
]

action_cards = [
    # Profession
    "You can change the profession to a new one from the deck",
    "Get a new profession card from the deck",
    "Reroll profession card for all players",
    # Baggage
    "Change your baggage to a new one from the deck",
    "Get a new baggage from the deck",
    "Change your baggage to a new one from the deck",
    "Swap the baggage with any player of your choice",
    "Reroll baggage card for all players",
    # Phobia
    "Swap phobia with any player of your choice",
    "Change the phobia to a new one from the deck",
    "Change the phobia to a new one from the deck",
    # Hobby
    "Reroll hobby card for all players",
    "Reroll hobby card for any player",
    "Reroll hobby card for any player",
    # Health
    "Swap health with the player to the right",
    "All players swap their health clockwise",
    "Swap health with any player of your choice",
    "Reroll health card for all players",
    "Swap your health card to a new one from the deck",
    "Heal any health problem, you are perfectly healthy",
    "Heal any health problem, you are perfectly healthy",
    # Additional Info
    "Swap additional info with the player to the right",
    "Change the additional info to a new one from the deck",
    # Sex/Age
    "This card allows you to reroll the sex/age card for any player",
    "This card allows you to reroll the sex/age card for any player",
    "This card allows you to reroll the sex/age card for all players",
    # Bunker
    "Bunker is stationed on the territory of the amusement park (20% destruction)",
    "Bunker is located next to a second bunker with two builders (2 healthy males)",
    "Bunker is located next to a second bunker with two nurses (2 healthy females)",
    "There is a second bunker located close to you, they aren't friendly (be careful)",
    "Bunker is located next to a second bunker with two strippers (2 healthy females)",
    "Bunker is located next to a second bunker with two chemists (2 healthy males)",
    "In order to win you need to get into the bunker without the player left of you, he is your enemy",
    "In order to win you need to get into the bunker with the player right of you, he is your friend",
    "The number of seats in the bunker was increased by one",
    "The number of seats in the bunker was decreased by one",
    "Reroll the bunker conditions",
    # Immunity
    "Acquire immunity for one round if your character has the most votes",
    "Give immunity for one round to the player of your choice (not yourself)",
    # Voting
    "Kick any player without voting",
    "Vote twice for any player of your choice",
    "Cancel one vote against yourself",
    "Take one vote from the player of your choice, now you have 2",
    "Mute one vote against you",
    # Items/Info
    "There is a wine basement 200 meters away from you",
    "Open any card of any player of your choice",
    "There is a gun storage 300 meters away from you",
    "Reveal health card of any player"
]

baggage_items = [
    "Multi-tool spork",
    "Solar-powered flashlight",
    "Invisible ink pen",
    "Bandage",
    "Self-warming socks",
    "Portable water purifier",
    "Duct tape roll with superhero patterns",
    "Compact sewing kit",
    "Pocket-sized plant",
    "Nutrient-rich energy bars",
    "Glow-in-the-dark playing cards",
    "Compact toolset",
    "Insulated water bottle",
    "Solar-powered phone charger",
    "Hula hoop with a built-in compass",
    "Confetti cannon (for morale-boosting celebrations)",
    "Portable hammock",
    "Firestarter kit",
    "Edible water bottles",
    "Lightweight sleeping bag",
    "Silly string spray (for distraction or emergency marking)",
    "Mood ring",
    "Emergency whistle",
    "Compact fire extinguisher",
    "Compact shovel",
    "Glow sticks",
    "Voice-changing megaphone (for communication)",
    "Scented candles with absurd scents (bacon, mac'n'cheese)",
    "Portable mini-golf set",
    "Compact folding knife"
    "Clown costume"
    "A watchdog"
    "A cat"
    "A child (2 years old, girl)"
    "A child (2 years old, boy)"
]

Useful_bunker = [
    "Mechanic shop",
    "Radio station/computer room",
    "Greenhouse",
    "Bible and old scripts",
    "Nurse room",
    "Emergency first aid kit",
    "Medieval weapon storage",
    "Medicine for asthma and mentally ill (one person)"
]

Useless_bunker = [
    "Media room with all seasons of office",
    "Poker room",
    "Pool table",
    "Paint room",
    "Weapon range without weapons",
    "Mannequins",
    "Tricycle",
    "Mousetrap"
]

Funny_bunker = [
    "A sex dungeon",
    "A box from shein",
    "Gachi collection",
    "A bunny in a hat",
    "Sex doll",
    "Joe Biden's sanity",
    "Your granny's old underwear",
    "Gender neutral toilet"
]

Catastrophe = [
    "Bioweapons",
    "World FLood",
    "Meteor Strike",
    "Chemical War",
    "Super Volcanoes",
    "Zombie-Virus",
    "Nuclear Catastrophe",
    "Hell on Earth",
    "AI-revolution",
    "Jurassic Park"
]